services:
  nginx:
    image: nginx:1.25.4
    container_name: grippymap-nginx
    depends_on:
      - tileserver
    env_file:
      - ./.env
    ports:
      - 80:80
    networks:
      - private
      - public
    volumes:
      - ./templates/nginx.conf:/etc/nginx/conf.d/revproxy.conf

  dbtools:
    image: grippymap/dbtools
    container_name: grippymap-dbtools
    depends_on:
      - postgis
    env_file:
      - ./.env
    networks:
      - private
  
    
  tileserver:
    image: grippymap/tileserver
    container_name: grippymap-tileserver
    depends_on:
      - postgis
    entrypoint: ["gunicorn", "-w", "${GUNICORN_WORKERS}", "main:app", "-b", "0.0.0.0:8128"]
    env_file:
      - ./.env
    networks:
      - private
      
  postgis:
    image: postgis/postgis:17-master
    container_name: grippymap-postgis
    env_file:
      - ./.env
    ports:
      - 5432:5432
    networks:
      - public
      - private
    volumes:
      - postgres:/var/lib/postgresql/data


networks:
  public:
    external: true
  private:
    external: false

volumes:
  postgres:
